version: "3.7"
services:
  frontend:
    build: ./frontend
    image: konabb-frontend
    container_name: konabb-frontend
  backend:
    build: ./backend
    image: konabb-backend
    container_name: konabb-backend
  db:
    image: mysql:8
    container_name: konabb-mysql
  cache:
    image: redis:5
    container_name: konabb-redis
networks:
  default:
    external:
      name: konabb