table! {
    use diesel::sql_types::*;

    /// Representation of the `boards` table.
    ///
    /// (Automatically generated by Diesel.)
    boards (board_id) {
        /// The `board_id` column of the `boards` table.
        ///
        /// Its SQL type is `Char`.
        ///
        /// (Automatically generated by Diesel.)
        board_id -> Char,
        /// The `name` column of the `boards` table.
        ///
        /// Its SQL type is `Char`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Char,
        /// The `short_name` column of the `boards` table.
        ///
        /// Its SQL type is `Char`.
        ///
        /// (Automatically generated by Diesel.)
        short_name -> Char,
        /// The `description` column of the `boards` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Nullable<Varchar>,
        /// The `board_type` column of the `boards` table.
        ///
        /// Its SQL type is `Unsigned<Tinyint>`.
        ///
        /// (Automatically generated by Diesel.)
        board_type -> Unsigned<Tinyint>,
        /// The `created_at` column of the `boards` table.
        ///
        /// Its SQL type is `Datetime`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Datetime,
        /// The `updated_at` column of the `boards` table.
        ///
        /// Its SQL type is `Nullable<Datetime>`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Nullable<Datetime>,
    }
}

table! {
    use diesel::sql_types::*;

    /// Representation of the `posts` table.
    ///
    /// (Automatically generated by Diesel.)
    posts (post_id) {
        /// The `post_id` column of the `posts` table.
        ///
        /// Its SQL type is `Char`.
        ///
        /// (Automatically generated by Diesel.)
        post_id -> Char,
        /// The `thread_id` column of the `posts` table.
        ///
        /// Its SQL type is `Char`.
        ///
        /// (Automatically generated by Diesel.)
        thread_id -> Char,
        /// The `user_id` column of the `posts` table.
        ///
        /// Its SQL type is `Nullable<Char>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Char>,
        /// The `raw_text` column of the `posts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        raw_text -> Text,
        /// The `rendered_text` column of the `posts` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        rendered_text -> Nullable<Text>,
        /// The `created_at` column of the `posts` table.
        ///
        /// Its SQL type is `Datetime`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Datetime,
        /// The `updated_at` column of the `posts` table.
        ///
        /// Its SQL type is `Nullable<Datetime>`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Nullable<Datetime>,
    }
}

table! {
    use diesel::sql_types::*;

    /// Representation of the `threads` table.
    ///
    /// (Automatically generated by Diesel.)
    threads (thread_id) {
        /// The `thread_id` column of the `threads` table.
        ///
        /// Its SQL type is `Char`.
        ///
        /// (Automatically generated by Diesel.)
        thread_id -> Char,
        /// The `board_id` column of the `threads` table.
        ///
        /// Its SQL type is `Char`.
        ///
        /// (Automatically generated by Diesel.)
        board_id -> Char,
        /// The `user_id` column of the `threads` table.
        ///
        /// Its SQL type is `Nullable<Char>`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Nullable<Char>,
        /// The `title` column of the `threads` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Varchar,
        /// The `created_at` column of the `threads` table.
        ///
        /// Its SQL type is `Datetime`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Datetime,
        /// The `updated_at` column of the `threads` table.
        ///
        /// Its SQL type is `Nullable<Datetime>`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Nullable<Datetime>,
    }
}

table! {
    use diesel::sql_types::*;

    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (user_id) {
        /// The `user_id` column of the `users` table.
        ///
        /// Its SQL type is `Char`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Char,
        /// The `username` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        username -> Varchar,
        /// The `email` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Nullable<Varchar>,
        /// The `password` column of the `users` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        password -> Varchar,
    }
}

joinable!(posts -> threads (thread_id));
joinable!(posts -> users (user_id));
joinable!(threads -> boards (board_id));
joinable!(threads -> users (user_id));

allow_tables_to_appear_in_same_query!(boards, posts, threads, users,);
